name: Generate Contribution Grid

on:
  schedule:
    - cron: "0 */12 * * *" # 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Contribution Grid SVG
        uses: arias-fede/github-contributions-graph@v1
        with:
          github_user: Shhuuuaaaa
          show_total_contributions: true
          show_streak: false
          color_0: "#161b22" 
          color_1: "#bfd6f6" 
          color_2: "#8dbdff" 
          color_3: "#4b91f1" 
          color_4: "#1a73e8" 

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
